# Generated by Django 4.2 on 2025-12-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
    ]
